name: 🚀 Deploy

on:
  workflow_call:
    inputs:
      environment:
        description: "Environment to deploy to (Preview/Production)"
        required: true
        type: string
      production:
        description: "Deploy to production"
        required: false
        default: false
        type: boolean
    outputs:
      deployment-url:
        description: "Deployment URL"
        value: ${{ jobs.deploy.outputs.deployment-url }}

jobs:
  deploy:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: ${{ steps.set-url.outputs.deployment-url }}
    outputs:
      deployment-url: ${{ steps.set-url.outputs.deployment-url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "npm"

      - name: Cache node_modules
        id: cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build application with OpenNext
        run: npx opennextjs-cloudflare build
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

      - name: Deploy to Cloudflare Workers
        id: deploy
        run: npx opennextjs-cloudflare deploy --env ${{ inputs.production && 'production' || 'preview' }}
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Set deployment URL
        id: set-url
        run: |
          PROJECT_NAME="neishastylist"
          if [ "${{ inputs.production }}" = "true" ]; then
            echo "deployment-url=<To Be Added>" >> $GITHUB_OUTPUT
          else
            echo "deployment-url=https://neishastylist-preview.treysouz.workers.dev" >> $GITHUB_OUTPUT
          fi
